---
title: "DATA 607 Assignment 1 - Anime Data"
author: "Muntasir"
date: "2026-09-03"
output: html_document
---
# Approach
For this assignment, I hope to use a MyAnmeList anime dataset that's found in the TidyTuesday GitHub repository. The core question to be answered is whether traits like genre, format, etc. are correlated to higher viewer ratings. I will start with a smaller data frame that contains variables most suitable for the question, with anime score being the primary output variable.
I will study the framework of the dataset and identify which columns are relevant for my investigation. I then hope to pinpoint those columns, providing succint labels and ensure categorical or numerical identifiers are showcased accordingly. It's also vital I look for columns that ought to be transformed in order to make data simpler to comprehend.
I should be ready for any data-related challenges. For instance, some show titles could have missing information when it coems to attributes while some shows might fall under several genres.I will need to outline these traits before determining how to present them through code. 